[package]
name = "rdot"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rdot"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["cargo", "derive", "string"] }
color-eyre = "0.5"
dirs-next = "2.0.0"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.4.2"

[dev-dependencies]
assert_cmd = "2.0.10"
predicates = "3.0.2"

# https://docs.rs/color-eyre/latest/color_eyre/#improving-perf-on-debug-builds
[profile.dev.package.backtrace]
opt-level = 3
