[package]
name = "rdot"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["cargo", "derive", "env", "string"] }
color-eyre = "0.5"
console = "0.15.5"
dialoguer = "0.10.3"
dirs-next = "2.0.0"
indicatif = "0.17.3"
lazy_static = "1.4.0"
log = "0.4.17"
serde = { version = "1.0", features = ["derive"] }
toml = "0.4.2"

[dev-dependencies]
assert_cmd = "2.0.10"
env_logger = "0.10.0"
predicates = "3.0.2"

# https://docs.rs/color-eyre/latest/color_eyre/#improving-perf-on-debug-builds
[profile.dev.package.backtrace]
opt-level = 3
